### ISSUE TITLE
5.5.3 config is broken

### ISSUE THREAD

**Issue by SawkeeReemo** [grzegorz914/homebridge-denon-tv#323]
After updating to 5.5.3, I can’t change anything in my config, and there is a red exclamation mark with the following notice. 

![Image](https://github.com/user-attachments/assets/b0ad6f7d-b601-4f64-af0a-b91ea057f712)

Even downgrading to an older version, it’s still broken. I’m running Homebridge in the official docker container, if that helps.

**Comment by SawkeeReemo** [comment]
Confirmed: This plugin doesn't seem to work on Homebridge UI after UI v.4.68.0. Once I rolled back to that UI version, the config is no longer broken.

**Comment by grzegorz914** [comment]
All mandatory properties need to be set, please check your config carefully.

**Comment by grzegorz914** [comment]
I’m on HB UI 5.0.0-beta and all is working fine

**Comment by horsenoggingit** [comment]
Same issue

**Comment by SawkeeReemo** [comment]
> Same issue. I can edit the json manually and everything seems to be working correctly, but I now have the same issues [@SawkeeReemo](https://github.com/SawkeeReemo) has with the "Plugin Config"

I noticed that as well. But I was t able to figure out how to get my volume lightbulb button to come back that way. Do you know how to do that?

**Comment by horsenoggingit** [comment]
> > Same issue. I can edit the json manually and everything seems to be working correctly, but I now have the same issues [@SawkeeReemo](https://github.com/SawkeeReemo) has with the "Plugin Config"
> 
> I noticed that as well. But I was t able to figure out how to get my volume lightbulb button to come back that way. Do you know how to do that?

Yes, you need to change "volumeControl" to "volumeControlType" looks like the json key was changed

**Comment by SawkeeReemo** [comment]
> All mandatory properties need to be set, please check your config carefully.

I can’t change anything. That’s the problem. Even if there is something missing, it won’t let me save it. Does UI 5.0 beta require Homebridge 2.0?  I’m on v1.9.0 due to plugin limitations. 

If I don’t need HB 2.0, I’ll give the 5.0 UI a shot. But I had to roll back to 4.68 in order to be able to edit my config again.

**Comment by SawkeeReemo** [comment]
> I’m on HB UI 5.0.0-beta and all is working fine

I bounced up to the latest 5.0 beta and can confirm that the config is not broken there. It’s only broken on official release versions v4.69.0 through v4.71.0.

**Comment by horsenoggingit** [comment]
This issue isn't exclusive to this plugin. homebridge-webos-tv has the same issue as well as 
"Settings -> UI Advanced Settings"

**Comment by SawkeeReemo** [comment]
> This issue isn't exclusive to this plugin. homebridge-webos-tv has the same issue as well as "Settings -> UI Advanced Settings" in Homebridge UI.

I came back here to say that on a computer it seems that the config is validated, but on mobile, specifically iOS when opened as a progressive web app (how I normally use Homebridge), the config shows as not valid. 

This may be a bug for Homebridge to sort out, not this plugin. 

For the record, homebridge-webos-tv is not giving me this issue.

**Comment by SawkeeReemo** [comment]
> > > Same issue. I can edit the json manually and everything seems to be working correctly, but I now have the same issues [@SawkeeReemo](https://github.com/SawkeeReemo) has with the "Plugin Config"
> > 
> > 
> > I noticed that as well. But I was t able to figure out how to get my volume lightbulb button to come back that way. Do you know how to do that?
> 
> Yes, you need to change "volumeControl" to "volumeControlType", looks like the json key was changed.
> 
> Honestly not the greatest thing for the developer to do, it breaks automations which take a long time to fix... there are still bugs with volume control, it doesn't handle dB volume well.

Thanks for this. Is the db issue you’re mentioning where it takes like 20 seconds for a volume change to register? I’ve been having that issue for a while, but I thought it was a HomeKit problem.

**Comment by grzegorz914** [comment]
The issue will be fixed today

**Comment by grzegorz914** [comment]
Fixed

**Comment by SawkeeReemo** [comment]
Was this meant to be fixed on v5.7.2? If so, I'm still seeing the issue on mobile.

![Image](https://github.com/user-attachments/assets/d8c867cc-03ed-428c-927d-6bd5e0b2dbb0)

**Comment by grzegorz914** [comment]
5.7.3

**Comment by SawkeeReemo** [comment]
Unfortunately, it’s still happening on 5.7.3 as well for me.

**Comment by grzegorz914** [comment]
Post your config json.
Here is all correct on mobile safari.

![Image](https://github.com/user-attachments/assets/5aa5b7c0-6e93-4a17-bebf-a98613a3fcbe)
